version: '3.4'

services:
  testcafe:
    volumes:
      - .:/app
      - /app/node_modules/
    build:
      context: .
      dockerfile: ./Docker/dockerfile

  backstop:
    volumes:
      - .:/app
      - /app/node_modules/
    build:
      context: .
      dockerfile: ./Docker/dockerfileBackstop

